name: 'My Job will help to Planning for display Message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: macOS-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
      - name: Install Python in Ubuntu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Execute some Linux Commands
        run: |
          echo "V6"
          date
          echo "V4"
          echo "V5"
          echo "V7"
          echo "v8"
          echo "V9"
          
